# model setting

model_name: EqStftAMPBC

model_info:
  M: 81
  rho: 1
  overlaps: 80
  strides: 161

# M <= strides
# FFT_size = strides + overlaps  for stft.

# data setting
train_data:
  path: /home/xiaoxinyu/pkufiber/data/80G_3ch_batch40.h5
  Nmodes: 2
  Nch_list: [3]
  Rs_list: [80]
  Pch_list: [3]
  strides: 322
  num_symb_per_mode: 800000
  truncate: 20000
  pre_transform: Rx_CDCDDLMS(taps=32,lr=[0.015625, 0.0078125])

test_data:
  path: /home/xiaoxinyu/TorchFiber/dataset_A800/test.h5
  Nmodes: 2
  Nch_list: [3]
  Rs_list: [80]
  Pch_list: [3]
  strides: 322
  num_symb_per_mode: 100000
  truncate: 20000
  pre_transform: Rx_CDCDDLMS(taps=32,lr=[0.015625, 0.0078125])


# training setting
seed: 1232
epochs: 30
save_interval: 10
batch_size: 100
test_batch_size: 100
# lr: 0.0000001
lr: 0.000001
lr_decay_step: 10
decay_gamma: 0.1
loss_type: mse
device: cuda:0
